name: Build & Deploy Mail Archiver

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    env:
      DOCKER_REGISTRY: 192.168.178.56:5000
      IMAGE_NAME: mailarchiver
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Show current directory
        run: pwd

      - name: List repository files
        run: ls -R

      # Docker Image bauen
      - name: Build Docker image
        run: |
          sudo docker build \
            -t $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG \
            -f ./NetMailArchiver.Web/Dockerfile \
            ./ 

      # Docker Image pushen
      - name: Push Docker image to local registry
        run: |
          sudo docker push $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      # Kubernetes Deployment mit neuem Image-Tag patchen
      - name: Update Kubernetes deployment image
        run: |
          kubectl set image deployment/mailarchiver \
          mailarchiver=$DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      # Rollout Ã¼berwachen
      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/mailarchiver
