name: Build & Deploy Mail Archiver

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    env:
      DOCKER_REGISTRY: 192.168.178.56:5000
      IMAGE_NAME: mailarchiver
      IMAGE_TAG: latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Show current directory (Debug)
        run: pwd

      - name: List repository files (Debug)
        run: ls -R

      - name: Build Docker image
        run: |
          sudo docker build -t $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG -f ./NetMailArchiver/Dockerfile ./NetMailArchiver

      - name: Push Docker image to local registry
        run: |
          sudo docker push $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/
